### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by szmsu2011** [szmsu2011/redq#1]
- [ ] Create changelog
- [ ] GitHub workflow: R CMD check and test coverage
- [ ] Incorporate tsibble data structure
- [ ] S3 print method for EDQ outputs
